select * from job1.f_t1();
select * from job1.f_t2();
select * from job1.f_t3();
select * from job1.f_t4();
select * from job1.f_t5();
select * from job1.f_t7();
select * from job1.f_t8();
select * from job1.f_t9();
select * from job1.f_t10();
