CREATE OR REPLACE PROCEDURE job1.p_t1(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t1 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t2(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t2 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t3(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t3 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t4(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t4 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t5(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t5 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t6(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t6 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t7(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t7 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t8(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t8 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t9(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t9 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job1.p_t10(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job1.t10 LIMIT 5;
END;
$$; 
