CREATE OR REPLACE FUNCTION job1.f_t1()
RETURNS SETOF job1.t1
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t1 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t2()
RETURNS SETOF job1.t2
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t2 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t3()
RETURNS SETOF job1.t3
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t3 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t4()
RETURNS SETOF job1.t4
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t4 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t5()
RETURNS SETOF job1.t5
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t5 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t6()
RETURNS SETOF job1.t6
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t6 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t7()
RETURNS SETOF job1.t7
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t7 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t8()
RETURNS SETOF job1.t8
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t8 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t9()
RETURNS SETOF job1.t9
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t9 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job1.f_t10()
RETURNS SETOF job1.t10
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job1.t10 LIMIT 5;
END;
$$;
