CREATE TABLE bench.tph1 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 bytea
    ,c4 timestamp
    ,c5 real
    ,c6 integer
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph1_p0 PARTITION OF bench.tph1 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE bench.tph1_p1 PARTITION OF bench.tph1 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE bench.tph1_p2 PARTITION OF bench.tph1 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE bench.tph1_p3 PARTITION OF bench.tph1 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE bench.tph1_p4 PARTITION OF bench.tph1 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE bench.tph1_p5 PARTITION OF bench.tph1 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE bench.tph2 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 boolean
    ,c4 date
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph2_p0 PARTITION OF bench.tph2 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE bench.tph2_p1 PARTITION OF bench.tph2 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE bench.tph2_p2 PARTITION OF bench.tph2 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE bench.tph2_p3 PARTITION OF bench.tph2 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE bench.tph2_p4 PARTITION OF bench.tph2 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE bench.tph2_p5 PARTITION OF bench.tph2 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE bench.tph2_p6 PARTITION OF bench.tph2 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE bench.tph3 (
    id BIGSERIAL
    ,c1 integer
    ,c2 smallint
    ,c3 smallint
    ,c4 varchar(50)
    ,c5 bigint
    ,c6 smallint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph3_p0 PARTITION OF bench.tph3 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE bench.tph3_p1 PARTITION OF bench.tph3 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE bench.tph3_p2 PARTITION OF bench.tph3 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE bench.tph3_p3 PARTITION OF bench.tph3 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE bench.tph3_p4 PARTITION OF bench.tph3 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE bench.tph3_p5 PARTITION OF bench.tph3 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE bench.tph3_p6 PARTITION OF bench.tph3 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE bench.tph3_p7 PARTITION OF bench.tph3 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE bench.tph4 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bigint
    ,c3 integer
    ,c4 varchar(4)
    ,c5 timestamp
    ,c6 date
    ,c7 bytea
    ,c8 integer
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph4_p0 PARTITION OF bench.tph4 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE bench.tph4_p1 PARTITION OF bench.tph4 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE bench.tph4_p2 PARTITION OF bench.tph4 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE bench.tph4_p3 PARTITION OF bench.tph4 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE bench.tph5 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 bigint
    ,c4 date
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph5_p0 PARTITION OF bench.tph5 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE bench.tph5_p1 PARTITION OF bench.tph5 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE bench.tph5_p2 PARTITION OF bench.tph5 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE bench.tph6 (
    id BIGSERIAL
    ,c1 integer
    ,c2 timestamp
    ,c3 boolean
    ,c4 uuid
    ,c5 double precision
    ,c6 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph6_p0 PARTITION OF bench.tph6 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE bench.tph6_p1 PARTITION OF bench.tph6 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE bench.tph6_p2 PARTITION OF bench.tph6 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE bench.tph6_p3 PARTITION OF bench.tph6 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE bench.tph6_p4 PARTITION OF bench.tph6 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE bench.tph6_p5 PARTITION OF bench.tph6 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE bench.tph6_p6 PARTITION OF bench.tph6 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE bench.tph7 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 date
    ,c4 integer
    ,c5 boolean
    ,c6 numeric(8,1)
    ,c7 bigint
    ,c8 bytea
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph7_p0 PARTITION OF bench.tph7 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE bench.tph7_p1 PARTITION OF bench.tph7 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE bench.tph7_p2 PARTITION OF bench.tph7 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE bench.tph7_p3 PARTITION OF bench.tph7 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE bench.tph7_p4 PARTITION OF bench.tph7 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE bench.tph7_p5 PARTITION OF bench.tph7 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE bench.tph7_p6 PARTITION OF bench.tph7 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE bench.tph8 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 date
    ,c4 bigint
    ,c5 real
    ,c6 date
    ,c7 bigint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph8_p0 PARTITION OF bench.tph8 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE bench.tph8_p1 PARTITION OF bench.tph8 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE bench.tph8_p2 PARTITION OF bench.tph8 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE bench.tph8_p3 PARTITION OF bench.tph8 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE bench.tph8_p4 PARTITION OF bench.tph8 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE bench.tph8_p5 PARTITION OF bench.tph8 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE bench.tph9 (
    id BIGSERIAL
    ,c1 integer
    ,c2 text
    ,c3 uuid
    ,c4 varchar(41)
    ,c5 timestamp
    ,c6 jsonb
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph9_p0 PARTITION OF bench.tph9 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE bench.tph9_p1 PARTITION OF bench.tph9 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE bench.tph9_p2 PARTITION OF bench.tph9 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE bench.tph10 (
    id BIGSERIAL
    ,c1 integer
    ,c2 date
    ,c3 boolean
    ,c4 bytea
    ,c5 varchar(8)
    ,c6 time
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE bench.tph10_p0 PARTITION OF bench.tph10 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE bench.tph10_p1 PARTITION OF bench.tph10 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE bench.tph10_p2 PARTITION OF bench.tph10 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE bench.tph10_p3 PARTITION OF bench.tph10 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE bench.tph10_p4 PARTITION OF bench.tph10 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE bench.tph10_p5 PARTITION OF bench.tph10 FOR VALUES WITH (MODULUS 6, REMAINDER 5);
