EXTENSION = rdb_sqltrc
MODULES = rdb_sqltrc
DATA = rdb_sqltrc--1.0.sql
PGFILEDESC = "RAO DB: rdb_sqltrc - SQL lifecycle tracer (parse/analyze/plan/execute)"
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)

