FROM python:3.11-alpine

WORKDIR /app
COPY file-producer.py python-modules.txt ./
RUN pip install --no-cache-dir -r python-modules.txt

RUN mkdir -p /data/incoming

ENV OUTPUT_DIR=/data/incoming
ENV INTERVAL_SECONDS=10
ENV MIN_ROWS=5
ENV MAX_ROWS=25

CMD ["python", "file-producer.py"]

