CREATE OR REPLACE FUNCTION part_range.f_t1()
RETURNS SETOF part_range.t1
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t1 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t2()
RETURNS SETOF part_range.t2
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t2 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t3()
RETURNS SETOF part_range.t3
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t3 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t4()
RETURNS SETOF part_range.t4
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t4 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t5()
RETURNS SETOF part_range.t5
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t5 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t6()
RETURNS SETOF part_range.t6
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t6 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t7()
RETURNS SETOF part_range.t7
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t7 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t8()
RETURNS SETOF part_range.t8
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t8 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t9()
RETURNS SETOF part_range.t9
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t9 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t10()
RETURNS SETOF part_range.t10
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t10 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t11()
RETURNS SETOF part_range.t11
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t11 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t12()
RETURNS SETOF part_range.t12
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t12 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t13()
RETURNS SETOF part_range.t13
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t13 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t14()
RETURNS SETOF part_range.t14
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t14 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t15()
RETURNS SETOF part_range.t15
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t15 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t16()
RETURNS SETOF part_range.t16
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t16 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t17()
RETURNS SETOF part_range.t17
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t17 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t18()
RETURNS SETOF part_range.t18
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t18 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t19()
RETURNS SETOF part_range.t19
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t19 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t20()
RETURNS SETOF part_range.t20
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t20 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t21()
RETURNS SETOF part_range.t21
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t21 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t22()
RETURNS SETOF part_range.t22
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t22 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t23()
RETURNS SETOF part_range.t23
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t23 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t24()
RETURNS SETOF part_range.t24
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t24 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t25()
RETURNS SETOF part_range.t25
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t25 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t26()
RETURNS SETOF part_range.t26
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t26 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t27()
RETURNS SETOF part_range.t27
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t27 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t28()
RETURNS SETOF part_range.t28
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t28 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t29()
RETURNS SETOF part_range.t29
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t29 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t30()
RETURNS SETOF part_range.t30
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t30 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t31()
RETURNS SETOF part_range.t31
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t31 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t32()
RETURNS SETOF part_range.t32
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t32 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t33()
RETURNS SETOF part_range.t33
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t33 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t34()
RETURNS SETOF part_range.t34
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t34 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t35()
RETURNS SETOF part_range.t35
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t35 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t36()
RETURNS SETOF part_range.t36
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t36 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t37()
RETURNS SETOF part_range.t37
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t37 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t38()
RETURNS SETOF part_range.t38
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t38 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t39()
RETURNS SETOF part_range.t39
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t39 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t40()
RETURNS SETOF part_range.t40
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t40 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t41()
RETURNS SETOF part_range.t41
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t41 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t42()
RETURNS SETOF part_range.t42
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t42 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t43()
RETURNS SETOF part_range.t43
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t43 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t44()
RETURNS SETOF part_range.t44
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t44 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t45()
RETURNS SETOF part_range.t45
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t45 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t46()
RETURNS SETOF part_range.t46
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t46 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t47()
RETURNS SETOF part_range.t47
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t47 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t48()
RETURNS SETOF part_range.t48
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t48 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t49()
RETURNS SETOF part_range.t49
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t49 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t50()
RETURNS SETOF part_range.t50
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t50 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t51()
RETURNS SETOF part_range.t51
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t51 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t52()
RETURNS SETOF part_range.t52
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t52 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t53()
RETURNS SETOF part_range.t53
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t53 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t54()
RETURNS SETOF part_range.t54
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t54 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t55()
RETURNS SETOF part_range.t55
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t55 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t56()
RETURNS SETOF part_range.t56
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t56 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t57()
RETURNS SETOF part_range.t57
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t57 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t58()
RETURNS SETOF part_range.t58
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t58 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t59()
RETURNS SETOF part_range.t59
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t59 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t60()
RETURNS SETOF part_range.t60
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t60 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t61()
RETURNS SETOF part_range.t61
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t61 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t62()
RETURNS SETOF part_range.t62
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t62 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t63()
RETURNS SETOF part_range.t63
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t63 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t64()
RETURNS SETOF part_range.t64
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t64 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t65()
RETURNS SETOF part_range.t65
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t65 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t66()
RETURNS SETOF part_range.t66
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t66 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t67()
RETURNS SETOF part_range.t67
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t67 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t68()
RETURNS SETOF part_range.t68
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t68 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t69()
RETURNS SETOF part_range.t69
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t69 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t70()
RETURNS SETOF part_range.t70
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t70 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t71()
RETURNS SETOF part_range.t71
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t71 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t72()
RETURNS SETOF part_range.t72
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t72 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t73()
RETURNS SETOF part_range.t73
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t73 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t74()
RETURNS SETOF part_range.t74
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t74 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t75()
RETURNS SETOF part_range.t75
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t75 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t76()
RETURNS SETOF part_range.t76
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t76 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t77()
RETURNS SETOF part_range.t77
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t77 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t78()
RETURNS SETOF part_range.t78
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t78 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t79()
RETURNS SETOF part_range.t79
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t79 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t80()
RETURNS SETOF part_range.t80
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t80 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t81()
RETURNS SETOF part_range.t81
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t81 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t82()
RETURNS SETOF part_range.t82
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t82 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t83()
RETURNS SETOF part_range.t83
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t83 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t84()
RETURNS SETOF part_range.t84
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t84 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t85()
RETURNS SETOF part_range.t85
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t85 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t86()
RETURNS SETOF part_range.t86
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t86 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t87()
RETURNS SETOF part_range.t87
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t87 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t88()
RETURNS SETOF part_range.t88
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t88 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t89()
RETURNS SETOF part_range.t89
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t89 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t90()
RETURNS SETOF part_range.t90
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t90 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t91()
RETURNS SETOF part_range.t91
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t91 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t92()
RETURNS SETOF part_range.t92
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t92 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t93()
RETURNS SETOF part_range.t93
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t93 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t94()
RETURNS SETOF part_range.t94
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t94 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t95()
RETURNS SETOF part_range.t95
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t95 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t96()
RETURNS SETOF part_range.t96
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t96 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t97()
RETURNS SETOF part_range.t97
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t97 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t98()
RETURNS SETOF part_range.t98
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t98 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t99()
RETURNS SETOF part_range.t99
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t99 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_range.f_t100()
RETURNS SETOF part_range.t100
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_range.t100 LIMIT 5;
END;
$$;
