CREATE TABLE part_hash.t1 (
    id BIGSERIAL
    ,c1 integer
    ,c2 date
    ,c3 jsonb
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t1_p0 PARTITION OF part_hash.t1 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t1_p1 PARTITION OF part_hash.t1 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t1_p2 PARTITION OF part_hash.t1 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t1_p3 PARTITION OF part_hash.t1 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t1_p4 PARTITION OF part_hash.t1 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t1_p5 PARTITION OF part_hash.t1 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t2 (
    id BIGSERIAL
    ,c1 integer
    ,c2 numeric(7,1)
    ,c3 numeric(10,0)
    ,c4 bigint
    ,c5 bytea
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t2_p0 PARTITION OF part_hash.t2 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t2_p1 PARTITION OF part_hash.t2 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t2_p2 PARTITION OF part_hash.t2 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t2_p3 PARTITION OF part_hash.t2 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t3 (
    id BIGSERIAL
    ,c1 integer
    ,c2 smallint
    ,c3 timestamp
    ,c4 boolean
    ,c5 integer
    ,c6 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t3_p0 PARTITION OF part_hash.t3 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t3_p1 PARTITION OF part_hash.t3 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t3_p2 PARTITION OF part_hash.t3 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t3_p3 PARTITION OF part_hash.t3 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t3_p4 PARTITION OF part_hash.t3 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t3_p5 PARTITION OF part_hash.t3 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t3_p6 PARTITION OF part_hash.t3 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t4 (
    id BIGSERIAL
    ,c1 integer
    ,c2 text
    ,c3 jsonb
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t4_p0 PARTITION OF part_hash.t4 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t4_p1 PARTITION OF part_hash.t4 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t4_p2 PARTITION OF part_hash.t4 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t4_p3 PARTITION OF part_hash.t4 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t5 (
    id BIGSERIAL
    ,c1 integer
    ,c2 jsonb
    ,c3 bigint
    ,c4 bigint
    ,c5 char(3)
    ,c6 real
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t5_p0 PARTITION OF part_hash.t5 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t5_p1 PARTITION OF part_hash.t5 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t5_p2 PARTITION OF part_hash.t5 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t5_p3 PARTITION OF part_hash.t5 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t5_p4 PARTITION OF part_hash.t5 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t6 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 text
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t6_p0 PARTITION OF part_hash.t6 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t6_p1 PARTITION OF part_hash.t6 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t6_p2 PARTITION OF part_hash.t6 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t6_p3 PARTITION OF part_hash.t6 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t6_p4 PARTITION OF part_hash.t6 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t6_p5 PARTITION OF part_hash.t6 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t7 (
    id BIGSERIAL
    ,c1 integer
    ,c2 varchar(46)
    ,c3 real
    ,c4 char(12)
    ,c5 bigint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t7_p0 PARTITION OF part_hash.t7 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t7_p1 PARTITION OF part_hash.t7 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t7_p2 PARTITION OF part_hash.t7 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t7_p3 PARTITION OF part_hash.t7 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t7_p4 PARTITION OF part_hash.t7 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t7_p5 PARTITION OF part_hash.t7 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t7_p6 PARTITION OF part_hash.t7 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t8 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 uuid
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t8_p0 PARTITION OF part_hash.t8 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t8_p1 PARTITION OF part_hash.t8 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t8_p2 PARTITION OF part_hash.t8 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t8_p3 PARTITION OF part_hash.t8 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t8_p4 PARTITION OF part_hash.t8 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t8_p5 PARTITION OF part_hash.t8 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t9 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 bytea
    ,c4 smallint
    ,c5 smallint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t9_p0 PARTITION OF part_hash.t9 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t9_p1 PARTITION OF part_hash.t9 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t9_p2 PARTITION OF part_hash.t9 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t9_p3 PARTITION OF part_hash.t9 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t9_p4 PARTITION OF part_hash.t9 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t9_p5 PARTITION OF part_hash.t9 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t9_p6 PARTITION OF part_hash.t9 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t9_p7 PARTITION OF part_hash.t9 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t10 (
    id BIGSERIAL
    ,c1 integer
    ,c2 timestamp
    ,c3 bytea
    ,c4 time
    ,c5 varchar(48)
    ,c6 smallint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t10_p0 PARTITION OF part_hash.t10 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t10_p1 PARTITION OF part_hash.t10 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t10_p2 PARTITION OF part_hash.t10 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t10_p3 PARTITION OF part_hash.t10 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t10_p4 PARTITION OF part_hash.t10 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t11 (
    id BIGSERIAL
    ,c1 integer
    ,c2 integer
    ,c3 time
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t11_p0 PARTITION OF part_hash.t11 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t11_p1 PARTITION OF part_hash.t11 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t11_p2 PARTITION OF part_hash.t11 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t11_p3 PARTITION OF part_hash.t11 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t11_p4 PARTITION OF part_hash.t11 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t11_p5 PARTITION OF part_hash.t11 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t11_p6 PARTITION OF part_hash.t11 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t11_p7 PARTITION OF part_hash.t11 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t12 (
    id BIGSERIAL
    ,c1 integer
    ,c2 jsonb
    ,c3 smallint
    ,c4 text
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t12_p0 PARTITION OF part_hash.t12 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t12_p1 PARTITION OF part_hash.t12 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t12_p2 PARTITION OF part_hash.t12 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t12_p3 PARTITION OF part_hash.t12 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t12_p4 PARTITION OF part_hash.t12 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t12_p5 PARTITION OF part_hash.t12 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t12_p6 PARTITION OF part_hash.t12 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t12_p7 PARTITION OF part_hash.t12 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t13 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bigint
    ,c3 jsonb
    ,c4 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t13_p0 PARTITION OF part_hash.t13 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t13_p1 PARTITION OF part_hash.t13 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t13_p2 PARTITION OF part_hash.t13 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t13_p3 PARTITION OF part_hash.t13 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t13_p4 PARTITION OF part_hash.t13 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t13_p5 PARTITION OF part_hash.t13 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t13_p6 PARTITION OF part_hash.t13 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t14 (
    id BIGSERIAL
    ,c1 integer
    ,c2 numeric(5,1)
    ,c3 boolean
    ,c4 bytea
    ,c5 char(7)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t14_p0 PARTITION OF part_hash.t14 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t14_p1 PARTITION OF part_hash.t14 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t14_p2 PARTITION OF part_hash.t14 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t14_p3 PARTITION OF part_hash.t14 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t14_p4 PARTITION OF part_hash.t14 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t15 (
    id BIGSERIAL
    ,c1 integer
    ,c2 date
    ,c3 real
    ,c4 char(1)
    ,c5 time
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t15_p0 PARTITION OF part_hash.t15 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t15_p1 PARTITION OF part_hash.t15 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t15_p2 PARTITION OF part_hash.t15 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t16 (
    id BIGSERIAL
    ,c1 integer
    ,c2 boolean
    ,c3 date
    ,c4 char(17)
    ,c5 bytea
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t16_p0 PARTITION OF part_hash.t16 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t16_p1 PARTITION OF part_hash.t16 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t16_p2 PARTITION OF part_hash.t16 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t16_p3 PARTITION OF part_hash.t16 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t16_p4 PARTITION OF part_hash.t16 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t16_p5 PARTITION OF part_hash.t16 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t17 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(5)
    ,c3 text
    ,c4 text
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t17_p0 PARTITION OF part_hash.t17 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t17_p1 PARTITION OF part_hash.t17 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t17_p2 PARTITION OF part_hash.t17 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t17_p3 PARTITION OF part_hash.t17 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t18 (
    id BIGSERIAL
    ,c1 integer
    ,c2 timestamp
    ,c3 boolean
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t18_p0 PARTITION OF part_hash.t18 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t18_p1 PARTITION OF part_hash.t18 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t18_p2 PARTITION OF part_hash.t18 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t18_p3 PARTITION OF part_hash.t18 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t18_p4 PARTITION OF part_hash.t18 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t18_p5 PARTITION OF part_hash.t18 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t19 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 text
    ,c4 jsonb
    ,c5 integer
    ,c6 varchar(49)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t19_p0 PARTITION OF part_hash.t19 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t19_p1 PARTITION OF part_hash.t19 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t19_p2 PARTITION OF part_hash.t19 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t20 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 jsonb
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t20_p0 PARTITION OF part_hash.t20 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t20_p1 PARTITION OF part_hash.t20 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t20_p2 PARTITION OF part_hash.t20 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t21 (
    id BIGSERIAL
    ,c1 integer
    ,c2 text
    ,c3 numeric(10,1)
    ,c4 time
    ,c5 varchar(39)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t21_p0 PARTITION OF part_hash.t21 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t21_p1 PARTITION OF part_hash.t21 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t21_p2 PARTITION OF part_hash.t21 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t21_p3 PARTITION OF part_hash.t21 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t22 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 text
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t22_p0 PARTITION OF part_hash.t22 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t22_p1 PARTITION OF part_hash.t22 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t22_p2 PARTITION OF part_hash.t22 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t22_p3 PARTITION OF part_hash.t22 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t23 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 time
    ,c4 timestamp
    ,c5 char(19)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t23_p0 PARTITION OF part_hash.t23 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t23_p1 PARTITION OF part_hash.t23 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t23_p2 PARTITION OF part_hash.t23 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t23_p3 PARTITION OF part_hash.t23 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t23_p4 PARTITION OF part_hash.t23 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t23_p5 PARTITION OF part_hash.t23 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t24 (
    id BIGSERIAL
    ,c1 integer
    ,c2 numeric(4,3)
    ,c3 date
    ,c4 boolean
    ,c5 boolean
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t24_p0 PARTITION OF part_hash.t24 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t24_p1 PARTITION OF part_hash.t24 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t24_p2 PARTITION OF part_hash.t24 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t24_p3 PARTITION OF part_hash.t24 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t24_p4 PARTITION OF part_hash.t24 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t25 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 varchar(8)
    ,c4 uuid
    ,c5 smallint
    ,c6 integer
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t25_p0 PARTITION OF part_hash.t25 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t25_p1 PARTITION OF part_hash.t25 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t25_p2 PARTITION OF part_hash.t25 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t25_p3 PARTITION OF part_hash.t25 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t25_p4 PARTITION OF part_hash.t25 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t25_p5 PARTITION OF part_hash.t25 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t25_p6 PARTITION OF part_hash.t25 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t26 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bigint
    ,c3 jsonb
    ,c4 bytea
    ,c5 varchar(38)
    ,c6 bytea
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t26_p0 PARTITION OF part_hash.t26 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t26_p1 PARTITION OF part_hash.t26 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t26_p2 PARTITION OF part_hash.t26 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t26_p3 PARTITION OF part_hash.t26 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t26_p4 PARTITION OF part_hash.t26 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t26_p5 PARTITION OF part_hash.t26 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t26_p6 PARTITION OF part_hash.t26 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t26_p7 PARTITION OF part_hash.t26 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t27 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 uuid
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t27_p0 PARTITION OF part_hash.t27 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t27_p1 PARTITION OF part_hash.t27 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t27_p2 PARTITION OF part_hash.t27 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t28 (
    id BIGSERIAL
    ,c1 integer
    ,c2 real
    ,c3 date
    ,c4 time
    ,c5 uuid
    ,c6 varchar(33)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t28_p0 PARTITION OF part_hash.t28 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t28_p1 PARTITION OF part_hash.t28 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t28_p2 PARTITION OF part_hash.t28 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t29 (
    id BIGSERIAL
    ,c1 integer
    ,c2 jsonb
    ,c3 time
    ,c4 integer
    ,c5 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t29_p0 PARTITION OF part_hash.t29 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t29_p1 PARTITION OF part_hash.t29 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t29_p2 PARTITION OF part_hash.t29 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t29_p3 PARTITION OF part_hash.t29 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t30 (
    id BIGSERIAL
    ,c1 integer
    ,c2 numeric(10,3)
    ,c3 jsonb
    ,c4 jsonb
    ,c5 numeric(6,3)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t30_p0 PARTITION OF part_hash.t30 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t30_p1 PARTITION OF part_hash.t30 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t30_p2 PARTITION OF part_hash.t30 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t31 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 text
    ,c4 double precision
    ,c5 jsonb
    ,c6 real
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t31_p0 PARTITION OF part_hash.t31 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t31_p1 PARTITION OF part_hash.t31 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t31_p2 PARTITION OF part_hash.t31 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t31_p3 PARTITION OF part_hash.t31 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t31_p4 PARTITION OF part_hash.t31 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t31_p5 PARTITION OF part_hash.t31 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t31_p6 PARTITION OF part_hash.t31 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t32 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 smallint
    ,c4 smallint
    ,c5 bytea
    ,c6 smallint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t32_p0 PARTITION OF part_hash.t32 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t32_p1 PARTITION OF part_hash.t32 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t32_p2 PARTITION OF part_hash.t32 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t32_p3 PARTITION OF part_hash.t32 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t33 (
    id BIGSERIAL
    ,c1 integer
    ,c2 timestamp
    ,c3 double precision
    ,c4 smallint
    ,c5 char(8)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t33_p0 PARTITION OF part_hash.t33 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t33_p1 PARTITION OF part_hash.t33 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t33_p2 PARTITION OF part_hash.t33 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t33_p3 PARTITION OF part_hash.t33 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t33_p4 PARTITION OF part_hash.t33 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t34 (
    id BIGSERIAL
    ,c1 integer
    ,c2 timestamp
    ,c3 time
    ,c4 real
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t34_p0 PARTITION OF part_hash.t34 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t34_p1 PARTITION OF part_hash.t34 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t34_p2 PARTITION OF part_hash.t34 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t34_p3 PARTITION OF part_hash.t34 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t34_p4 PARTITION OF part_hash.t34 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t34_p5 PARTITION OF part_hash.t34 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t34_p6 PARTITION OF part_hash.t34 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t34_p7 PARTITION OF part_hash.t34 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t35 (
    id BIGSERIAL
    ,c1 integer
    ,c2 numeric(6,2)
    ,c3 boolean
    ,c4 double precision
    ,c5 char(20)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t35_p0 PARTITION OF part_hash.t35 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t35_p1 PARTITION OF part_hash.t35 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t35_p2 PARTITION OF part_hash.t35 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t35_p3 PARTITION OF part_hash.t35 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t36 (
    id BIGSERIAL
    ,c1 integer
    ,c2 smallint
    ,c3 varchar(17)
    ,c4 integer
    ,c5 uuid
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t36_p0 PARTITION OF part_hash.t36 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t36_p1 PARTITION OF part_hash.t36 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t36_p2 PARTITION OF part_hash.t36 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t36_p3 PARTITION OF part_hash.t36 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t36_p4 PARTITION OF part_hash.t36 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t37 (
    id BIGSERIAL
    ,c1 integer
    ,c2 integer
    ,c3 jsonb
    ,c4 boolean
    ,c5 double precision
    ,c6 uuid
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t37_p0 PARTITION OF part_hash.t37 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t37_p1 PARTITION OF part_hash.t37 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t37_p2 PARTITION OF part_hash.t37 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t37_p3 PARTITION OF part_hash.t37 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t37_p4 PARTITION OF part_hash.t37 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t37_p5 PARTITION OF part_hash.t37 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t37_p6 PARTITION OF part_hash.t37 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t37_p7 PARTITION OF part_hash.t37 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t38 (
    id BIGSERIAL
    ,c1 integer
    ,c2 varchar(38)
    ,c3 text
    ,c4 integer
    ,c5 time
    ,c6 text
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t38_p0 PARTITION OF part_hash.t38 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t38_p1 PARTITION OF part_hash.t38 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t38_p2 PARTITION OF part_hash.t38 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t38_p3 PARTITION OF part_hash.t38 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t39 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(20)
    ,c3 timestamp
    ,c4 text
    ,c5 integer
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t39_p0 PARTITION OF part_hash.t39 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t39_p1 PARTITION OF part_hash.t39 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t39_p2 PARTITION OF part_hash.t39 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t39_p3 PARTITION OF part_hash.t39 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t39_p4 PARTITION OF part_hash.t39 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t39_p5 PARTITION OF part_hash.t39 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t39_p6 PARTITION OF part_hash.t39 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t40 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 bigint
    ,c4 bigint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t40_p0 PARTITION OF part_hash.t40 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t40_p1 PARTITION OF part_hash.t40 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t40_p2 PARTITION OF part_hash.t40 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t40_p3 PARTITION OF part_hash.t40 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t40_p4 PARTITION OF part_hash.t40 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t40_p5 PARTITION OF part_hash.t40 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t41 (
    id BIGSERIAL
    ,c1 integer
    ,c2 boolean
    ,c3 time
    ,c4 char(10)
    ,c5 boolean
    ,c6 smallint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t41_p0 PARTITION OF part_hash.t41 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t41_p1 PARTITION OF part_hash.t41 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t41_p2 PARTITION OF part_hash.t41 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t41_p3 PARTITION OF part_hash.t41 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t41_p4 PARTITION OF part_hash.t41 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t41_p5 PARTITION OF part_hash.t41 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t41_p6 PARTITION OF part_hash.t41 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t41_p7 PARTITION OF part_hash.t41 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t42 (
    id BIGSERIAL
    ,c1 integer
    ,c2 date
    ,c3 text
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t42_p0 PARTITION OF part_hash.t42 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t42_p1 PARTITION OF part_hash.t42 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t42_p2 PARTITION OF part_hash.t42 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t42_p3 PARTITION OF part_hash.t42 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t43 (
    id BIGSERIAL
    ,c1 integer
    ,c2 double precision
    ,c3 numeric(12,0)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t43_p0 PARTITION OF part_hash.t43 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t43_p1 PARTITION OF part_hash.t43 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t43_p2 PARTITION OF part_hash.t43 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t44 (
    id BIGSERIAL
    ,c1 integer
    ,c2 double precision
    ,c3 numeric(8,0)
    ,c4 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t44_p0 PARTITION OF part_hash.t44 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t44_p1 PARTITION OF part_hash.t44 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t44_p2 PARTITION OF part_hash.t44 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t44_p3 PARTITION OF part_hash.t44 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t44_p4 PARTITION OF part_hash.t44 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t45 (
    id BIGSERIAL
    ,c1 integer
    ,c2 smallint
    ,c3 integer
    ,c4 varchar(33)
    ,c5 bigint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t45_p0 PARTITION OF part_hash.t45 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t45_p1 PARTITION OF part_hash.t45 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t45_p2 PARTITION OF part_hash.t45 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t45_p3 PARTITION OF part_hash.t45 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t45_p4 PARTITION OF part_hash.t45 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t45_p5 PARTITION OF part_hash.t45 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t45_p6 PARTITION OF part_hash.t45 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t46 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(9)
    ,c3 bytea
    ,c4 bytea
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t46_p0 PARTITION OF part_hash.t46 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t46_p1 PARTITION OF part_hash.t46 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t46_p2 PARTITION OF part_hash.t46 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t46_p3 PARTITION OF part_hash.t46 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t46_p4 PARTITION OF part_hash.t46 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t47 (
    id BIGSERIAL
    ,c1 integer
    ,c2 varchar(15)
    ,c3 real
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t47_p0 PARTITION OF part_hash.t47 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t47_p1 PARTITION OF part_hash.t47 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t47_p2 PARTITION OF part_hash.t47 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t48 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 boolean
    ,c4 char(9)
    ,c5 boolean
    ,c6 smallint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t48_p0 PARTITION OF part_hash.t48 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t48_p1 PARTITION OF part_hash.t48 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t48_p2 PARTITION OF part_hash.t48 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t48_p3 PARTITION OF part_hash.t48 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t48_p4 PARTITION OF part_hash.t48 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t48_p5 PARTITION OF part_hash.t48 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t49 (
    id BIGSERIAL
    ,c1 integer
    ,c2 date
    ,c3 text
    ,c4 real
    ,c5 integer
    ,c6 numeric(5,2)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t49_p0 PARTITION OF part_hash.t49 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t49_p1 PARTITION OF part_hash.t49 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t49_p2 PARTITION OF part_hash.t49 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t50 (
    id BIGSERIAL
    ,c1 integer
    ,c2 timestamp
    ,c3 bigint
    ,c4 varchar(37)
    ,c5 numeric(5,1)
    ,c6 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t50_p0 PARTITION OF part_hash.t50 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t50_p1 PARTITION OF part_hash.t50 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t50_p2 PARTITION OF part_hash.t50 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t50_p3 PARTITION OF part_hash.t50 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t50_p4 PARTITION OF part_hash.t50 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t50_p5 PARTITION OF part_hash.t50 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t50_p6 PARTITION OF part_hash.t50 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t50_p7 PARTITION OF part_hash.t50 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t51 (
    id BIGSERIAL
    ,c1 integer
    ,c2 varchar(30)
    ,c3 bytea
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t51_p0 PARTITION OF part_hash.t51 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t51_p1 PARTITION OF part_hash.t51 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t51_p2 PARTITION OF part_hash.t51 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t51_p3 PARTITION OF part_hash.t51 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t51_p4 PARTITION OF part_hash.t51 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t51_p5 PARTITION OF part_hash.t51 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t51_p6 PARTITION OF part_hash.t51 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t52 (
    id BIGSERIAL
    ,c1 integer
    ,c2 numeric(7,2)
    ,c3 uuid
    ,c4 boolean
    ,c5 numeric(7,3)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t52_p0 PARTITION OF part_hash.t52 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t52_p1 PARTITION OF part_hash.t52 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t52_p2 PARTITION OF part_hash.t52 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t52_p3 PARTITION OF part_hash.t52 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t52_p4 PARTITION OF part_hash.t52 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t52_p5 PARTITION OF part_hash.t52 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t52_p6 PARTITION OF part_hash.t52 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t53 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 time
    ,c4 time
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t53_p0 PARTITION OF part_hash.t53 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t53_p1 PARTITION OF part_hash.t53 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t53_p2 PARTITION OF part_hash.t53 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t53_p3 PARTITION OF part_hash.t53 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t53_p4 PARTITION OF part_hash.t53 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t54 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(15)
    ,c3 text
    ,c4 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t54_p0 PARTITION OF part_hash.t54 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t54_p1 PARTITION OF part_hash.t54 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t54_p2 PARTITION OF part_hash.t54 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t54_p3 PARTITION OF part_hash.t54 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t54_p4 PARTITION OF part_hash.t54 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t54_p5 PARTITION OF part_hash.t54 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t54_p6 PARTITION OF part_hash.t54 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t55 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 date
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t55_p0 PARTITION OF part_hash.t55 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t55_p1 PARTITION OF part_hash.t55 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t55_p2 PARTITION OF part_hash.t55 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t55_p3 PARTITION OF part_hash.t55 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t55_p4 PARTITION OF part_hash.t55 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t55_p5 PARTITION OF part_hash.t55 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t55_p6 PARTITION OF part_hash.t55 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t56 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 smallint
    ,c4 numeric(12,2)
    ,c5 varchar(23)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t56_p0 PARTITION OF part_hash.t56 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t56_p1 PARTITION OF part_hash.t56 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t56_p2 PARTITION OF part_hash.t56 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t57 (
    id BIGSERIAL
    ,c1 integer
    ,c2 integer
    ,c3 jsonb
    ,c4 uuid
    ,c5 bytea
    ,c6 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t57_p0 PARTITION OF part_hash.t57 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t57_p1 PARTITION OF part_hash.t57 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t57_p2 PARTITION OF part_hash.t57 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t57_p3 PARTITION OF part_hash.t57 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t57_p4 PARTITION OF part_hash.t57 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t57_p5 PARTITION OF part_hash.t57 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t58 (
    id BIGSERIAL
    ,c1 integer
    ,c2 varchar(42)
    ,c3 jsonb
    ,c4 bigint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t58_p0 PARTITION OF part_hash.t58 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t58_p1 PARTITION OF part_hash.t58 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t58_p2 PARTITION OF part_hash.t58 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t58_p3 PARTITION OF part_hash.t58 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t58_p4 PARTITION OF part_hash.t58 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t58_p5 PARTITION OF part_hash.t58 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t59 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(7)
    ,c3 real
    ,c4 smallint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t59_p0 PARTITION OF part_hash.t59 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t59_p1 PARTITION OF part_hash.t59 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t59_p2 PARTITION OF part_hash.t59 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t59_p3 PARTITION OF part_hash.t59 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t59_p4 PARTITION OF part_hash.t59 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t59_p5 PARTITION OF part_hash.t59 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t60 (
    id BIGSERIAL
    ,c1 integer
    ,c2 text
    ,c3 real
    ,c4 varchar(1)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t60_p0 PARTITION OF part_hash.t60 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t60_p1 PARTITION OF part_hash.t60 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t60_p2 PARTITION OF part_hash.t60 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t60_p3 PARTITION OF part_hash.t60 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t60_p4 PARTITION OF part_hash.t60 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t60_p5 PARTITION OF part_hash.t60 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t60_p6 PARTITION OF part_hash.t60 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t60_p7 PARTITION OF part_hash.t60 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t61 (
    id BIGSERIAL
    ,c1 integer
    ,c2 boolean
    ,c3 timestamp
    ,c4 boolean
    ,c5 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t61_p0 PARTITION OF part_hash.t61 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t61_p1 PARTITION OF part_hash.t61 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t61_p2 PARTITION OF part_hash.t61 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t62 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bigint
    ,c3 smallint
    ,c4 uuid
    ,c5 timestamp
    ,c6 uuid
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t62_p0 PARTITION OF part_hash.t62 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t62_p1 PARTITION OF part_hash.t62 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t62_p2 PARTITION OF part_hash.t62 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t62_p3 PARTITION OF part_hash.t62 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t62_p4 PARTITION OF part_hash.t62 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t62_p5 PARTITION OF part_hash.t62 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t63 (
    id BIGSERIAL
    ,c1 integer
    ,c2 double precision
    ,c3 time
    ,c4 boolean
    ,c5 real
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t63_p0 PARTITION OF part_hash.t63 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t63_p1 PARTITION OF part_hash.t63 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t63_p2 PARTITION OF part_hash.t63 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t64 (
    id BIGSERIAL
    ,c1 integer
    ,c2 integer
    ,c3 boolean
    ,c4 double precision
    ,c5 jsonb
    ,c6 uuid
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t64_p0 PARTITION OF part_hash.t64 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t64_p1 PARTITION OF part_hash.t64 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t64_p2 PARTITION OF part_hash.t64 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t64_p3 PARTITION OF part_hash.t64 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t64_p4 PARTITION OF part_hash.t64 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t64_p5 PARTITION OF part_hash.t64 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t64_p6 PARTITION OF part_hash.t64 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t65 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 date
    ,c4 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t65_p0 PARTITION OF part_hash.t65 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t65_p1 PARTITION OF part_hash.t65 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t65_p2 PARTITION OF part_hash.t65 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t65_p3 PARTITION OF part_hash.t65 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t65_p4 PARTITION OF part_hash.t65 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t65_p5 PARTITION OF part_hash.t65 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t65_p6 PARTITION OF part_hash.t65 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t65_p7 PARTITION OF part_hash.t65 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t66 (
    id BIGSERIAL
    ,c1 integer
    ,c2 numeric(8,3)
    ,c3 double precision
    ,c4 double precision
    ,c5 time
    ,c6 varchar(47)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t66_p0 PARTITION OF part_hash.t66 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t66_p1 PARTITION OF part_hash.t66 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t66_p2 PARTITION OF part_hash.t66 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t66_p3 PARTITION OF part_hash.t66 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t66_p4 PARTITION OF part_hash.t66 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t66_p5 PARTITION OF part_hash.t66 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t67 (
    id BIGSERIAL
    ,c1 integer
    ,c2 boolean
    ,c3 real
    ,c4 jsonb
    ,c5 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t67_p0 PARTITION OF part_hash.t67 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t67_p1 PARTITION OF part_hash.t67 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t67_p2 PARTITION OF part_hash.t67 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t67_p3 PARTITION OF part_hash.t67 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t67_p4 PARTITION OF part_hash.t67 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t67_p5 PARTITION OF part_hash.t67 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t67_p6 PARTITION OF part_hash.t67 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t68 (
    id BIGSERIAL
    ,c1 integer
    ,c2 jsonb
    ,c3 char(17)
    ,c4 real
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t68_p0 PARTITION OF part_hash.t68 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t68_p1 PARTITION OF part_hash.t68 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t68_p2 PARTITION OF part_hash.t68 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t68_p3 PARTITION OF part_hash.t68 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t68_p4 PARTITION OF part_hash.t68 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t68_p5 PARTITION OF part_hash.t68 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t69 (
    id BIGSERIAL
    ,c1 integer
    ,c2 jsonb
    ,c3 date
    ,c4 numeric(5,0)
    ,c5 char(16)
    ,c6 bytea
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t69_p0 PARTITION OF part_hash.t69 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t69_p1 PARTITION OF part_hash.t69 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t69_p2 PARTITION OF part_hash.t69 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t70 (
    id BIGSERIAL
    ,c1 integer
    ,c2 real
    ,c3 jsonb
    ,c4 jsonb
    ,c5 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t70_p0 PARTITION OF part_hash.t70 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t70_p1 PARTITION OF part_hash.t70 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t70_p2 PARTITION OF part_hash.t70 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t70_p3 PARTITION OF part_hash.t70 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t71 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(19)
    ,c3 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t71_p0 PARTITION OF part_hash.t71 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t71_p1 PARTITION OF part_hash.t71 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t71_p2 PARTITION OF part_hash.t71 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t71_p3 PARTITION OF part_hash.t71 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t71_p4 PARTITION OF part_hash.t71 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t71_p5 PARTITION OF part_hash.t71 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t71_p6 PARTITION OF part_hash.t71 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t71_p7 PARTITION OF part_hash.t71 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t72 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 varchar(1)
    ,c4 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t72_p0 PARTITION OF part_hash.t72 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t72_p1 PARTITION OF part_hash.t72 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t72_p2 PARTITION OF part_hash.t72 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t72_p3 PARTITION OF part_hash.t72 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t73 (
    id BIGSERIAL
    ,c1 integer
    ,c2 smallint
    ,c3 bigint
    ,c4 bytea
    ,c5 bytea
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t73_p0 PARTITION OF part_hash.t73 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t73_p1 PARTITION OF part_hash.t73 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t73_p2 PARTITION OF part_hash.t73 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t73_p3 PARTITION OF part_hash.t73 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t74 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 boolean
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t74_p0 PARTITION OF part_hash.t74 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t74_p1 PARTITION OF part_hash.t74 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t74_p2 PARTITION OF part_hash.t74 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t74_p3 PARTITION OF part_hash.t74 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t75 (
    id BIGSERIAL
    ,c1 integer
    ,c2 time
    ,c3 numeric(6,1)
    ,c4 smallint
    ,c5 varchar(28)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t75_p0 PARTITION OF part_hash.t75 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t75_p1 PARTITION OF part_hash.t75 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t75_p2 PARTITION OF part_hash.t75 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t75_p3 PARTITION OF part_hash.t75 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t75_p4 PARTITION OF part_hash.t75 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t76 (
    id BIGSERIAL
    ,c1 integer
    ,c2 jsonb
    ,c3 bytea
    ,c4 jsonb
    ,c5 bigint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t76_p0 PARTITION OF part_hash.t76 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t76_p1 PARTITION OF part_hash.t76 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t76_p2 PARTITION OF part_hash.t76 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t76_p3 PARTITION OF part_hash.t76 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t76_p4 PARTITION OF part_hash.t76 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t77 (
    id BIGSERIAL
    ,c1 integer
    ,c2 boolean
    ,c3 text
    ,c4 text
    ,c5 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t77_p0 PARTITION OF part_hash.t77 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t77_p1 PARTITION OF part_hash.t77 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t77_p2 PARTITION OF part_hash.t77 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t77_p3 PARTITION OF part_hash.t77 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t77_p4 PARTITION OF part_hash.t77 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t77_p5 PARTITION OF part_hash.t77 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t77_p6 PARTITION OF part_hash.t77 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t77_p7 PARTITION OF part_hash.t77 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t78 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(13)
    ,c3 double precision
    ,c4 smallint
    ,c5 smallint
    ,c6 date
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t78_p0 PARTITION OF part_hash.t78 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t78_p1 PARTITION OF part_hash.t78 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t78_p2 PARTITION OF part_hash.t78 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t78_p3 PARTITION OF part_hash.t78 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t78_p4 PARTITION OF part_hash.t78 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t78_p5 PARTITION OF part_hash.t78 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t78_p6 PARTITION OF part_hash.t78 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t79 (
    id BIGSERIAL
    ,c1 integer
    ,c2 text
    ,c3 varchar(36)
    ,c4 bytea
    ,c5 bigint
    ,c6 timestamp
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t79_p0 PARTITION OF part_hash.t79 FOR VALUES WITH (MODULUS 7, REMAINDER 0);
CREATE TABLE part_hash.t79_p1 PARTITION OF part_hash.t79 FOR VALUES WITH (MODULUS 7, REMAINDER 1);
CREATE TABLE part_hash.t79_p2 PARTITION OF part_hash.t79 FOR VALUES WITH (MODULUS 7, REMAINDER 2);
CREATE TABLE part_hash.t79_p3 PARTITION OF part_hash.t79 FOR VALUES WITH (MODULUS 7, REMAINDER 3);
CREATE TABLE part_hash.t79_p4 PARTITION OF part_hash.t79 FOR VALUES WITH (MODULUS 7, REMAINDER 4);
CREATE TABLE part_hash.t79_p5 PARTITION OF part_hash.t79 FOR VALUES WITH (MODULUS 7, REMAINDER 5);
CREATE TABLE part_hash.t79_p6 PARTITION OF part_hash.t79 FOR VALUES WITH (MODULUS 7, REMAINDER 6);

CREATE TABLE part_hash.t80 (
    id BIGSERIAL
    ,c1 integer
    ,c2 timestamp
    ,c3 integer
    ,c4 integer
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t80_p0 PARTITION OF part_hash.t80 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t80_p1 PARTITION OF part_hash.t80 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t80_p2 PARTITION OF part_hash.t80 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t80_p3 PARTITION OF part_hash.t80 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t81 (
    id BIGSERIAL
    ,c1 integer
    ,c2 real
    ,c3 char(12)
    ,c4 numeric(9,1)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t81_p0 PARTITION OF part_hash.t81 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t81_p1 PARTITION OF part_hash.t81 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t81_p2 PARTITION OF part_hash.t81 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t81_p3 PARTITION OF part_hash.t81 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t81_p4 PARTITION OF part_hash.t81 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t82 (
    id BIGSERIAL
    ,c1 integer
    ,c2 boolean
    ,c3 timestamp
    ,c4 varchar(11)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t82_p0 PARTITION OF part_hash.t82 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t82_p1 PARTITION OF part_hash.t82 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t82_p2 PARTITION OF part_hash.t82 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t82_p3 PARTITION OF part_hash.t82 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t82_p4 PARTITION OF part_hash.t82 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t82_p5 PARTITION OF part_hash.t82 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t83 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bigint
    ,c3 bytea
    ,c4 char(3)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t83_p0 PARTITION OF part_hash.t83 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t83_p1 PARTITION OF part_hash.t83 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t83_p2 PARTITION OF part_hash.t83 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t84 (
    id BIGSERIAL
    ,c1 integer
    ,c2 varchar(31)
    ,c3 real
    ,c4 real
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t84_p0 PARTITION OF part_hash.t84 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t84_p1 PARTITION OF part_hash.t84 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t84_p2 PARTITION OF part_hash.t84 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t84_p3 PARTITION OF part_hash.t84 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t85 (
    id BIGSERIAL
    ,c1 integer
    ,c2 smallint
    ,c3 bytea
    ,c4 date
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t85_p0 PARTITION OF part_hash.t85 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t85_p1 PARTITION OF part_hash.t85 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t85_p2 PARTITION OF part_hash.t85 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t86 (
    id BIGSERIAL
    ,c1 integer
    ,c2 text
    ,c3 text
    ,c4 bytea
    ,c5 jsonb
    ,c6 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t86_p0 PARTITION OF part_hash.t86 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t86_p1 PARTITION OF part_hash.t86 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t86_p2 PARTITION OF part_hash.t86 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t86_p3 PARTITION OF part_hash.t86 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t87 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(12)
    ,c3 text
    ,c4 boolean
    ,c5 bigint
    ,c6 jsonb
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t87_p0 PARTITION OF part_hash.t87 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t87_p1 PARTITION OF part_hash.t87 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t87_p2 PARTITION OF part_hash.t87 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t87_p3 PARTITION OF part_hash.t87 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t87_p4 PARTITION OF part_hash.t87 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t87_p5 PARTITION OF part_hash.t87 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t87_p6 PARTITION OF part_hash.t87 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t87_p7 PARTITION OF part_hash.t87 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t88 (
    id BIGSERIAL
    ,c1 integer
    ,c2 integer
    ,c3 smallint
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t88_p0 PARTITION OF part_hash.t88 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t88_p1 PARTITION OF part_hash.t88 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t88_p2 PARTITION OF part_hash.t88 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t88_p3 PARTITION OF part_hash.t88 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t89 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 bigint
    ,c4 bigint
    ,c5 jsonb
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t89_p0 PARTITION OF part_hash.t89 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t89_p1 PARTITION OF part_hash.t89 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t89_p2 PARTITION OF part_hash.t89 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t89_p3 PARTITION OF part_hash.t89 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t89_p4 PARTITION OF part_hash.t89 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t90 (
    id BIGSERIAL
    ,c1 integer
    ,c2 integer
    ,c3 timestamp
    ,c4 date
    ,c5 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t90_p0 PARTITION OF part_hash.t90 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t90_p1 PARTITION OF part_hash.t90 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t90_p2 PARTITION OF part_hash.t90 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t91 (
    id BIGSERIAL
    ,c1 integer
    ,c2 jsonb
    ,c3 text
    ,c4 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t91_p0 PARTITION OF part_hash.t91 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t91_p1 PARTITION OF part_hash.t91 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t91_p2 PARTITION OF part_hash.t91 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t92 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bytea
    ,c3 jsonb
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t92_p0 PARTITION OF part_hash.t92 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t92_p1 PARTITION OF part_hash.t92 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t92_p2 PARTITION OF part_hash.t92 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t92_p3 PARTITION OF part_hash.t92 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t92_p4 PARTITION OF part_hash.t92 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t92_p5 PARTITION OF part_hash.t92 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t93 (
    id BIGSERIAL
    ,c1 integer
    ,c2 timestamp
    ,c3 smallint
    ,c4 real
    ,c5 uuid
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t93_p0 PARTITION OF part_hash.t93 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t93_p1 PARTITION OF part_hash.t93 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t93_p2 PARTITION OF part_hash.t93 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t93_p3 PARTITION OF part_hash.t93 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t93_p4 PARTITION OF part_hash.t93 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t93_p5 PARTITION OF part_hash.t93 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t94 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(19)
    ,c3 integer
    ,c4 char(14)
    ,c5 char(11)
    ,c6 time
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t94_p0 PARTITION OF part_hash.t94 FOR VALUES WITH (MODULUS 6, REMAINDER 0);
CREATE TABLE part_hash.t94_p1 PARTITION OF part_hash.t94 FOR VALUES WITH (MODULUS 6, REMAINDER 1);
CREATE TABLE part_hash.t94_p2 PARTITION OF part_hash.t94 FOR VALUES WITH (MODULUS 6, REMAINDER 2);
CREATE TABLE part_hash.t94_p3 PARTITION OF part_hash.t94 FOR VALUES WITH (MODULUS 6, REMAINDER 3);
CREATE TABLE part_hash.t94_p4 PARTITION OF part_hash.t94 FOR VALUES WITH (MODULUS 6, REMAINDER 4);
CREATE TABLE part_hash.t94_p5 PARTITION OF part_hash.t94 FOR VALUES WITH (MODULUS 6, REMAINDER 5);

CREATE TABLE part_hash.t95 (
    id BIGSERIAL
    ,c1 integer
    ,c2 uuid
    ,c3 uuid
    ,c4 bigint
    ,c5 bytea
    ,c6 uuid
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t95_p0 PARTITION OF part_hash.t95 FOR VALUES WITH (MODULUS 3, REMAINDER 0);
CREATE TABLE part_hash.t95_p1 PARTITION OF part_hash.t95 FOR VALUES WITH (MODULUS 3, REMAINDER 1);
CREATE TABLE part_hash.t95_p2 PARTITION OF part_hash.t95 FOR VALUES WITH (MODULUS 3, REMAINDER 2);

CREATE TABLE part_hash.t96 (
    id BIGSERIAL
    ,c1 integer
    ,c2 boolean
    ,c3 char(1)
    ,c4 jsonb
    ,c5 varchar(7)
    ,c6 double precision
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t96_p0 PARTITION OF part_hash.t96 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t96_p1 PARTITION OF part_hash.t96 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t96_p2 PARTITION OF part_hash.t96 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t96_p3 PARTITION OF part_hash.t96 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

CREATE TABLE part_hash.t97 (
    id BIGSERIAL
    ,c1 integer
    ,c2 boolean
    ,c3 integer
    ,c4 boolean
    ,c5 numeric(10,0)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t97_p0 PARTITION OF part_hash.t97 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t97_p1 PARTITION OF part_hash.t97 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t97_p2 PARTITION OF part_hash.t97 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t97_p3 PARTITION OF part_hash.t97 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t97_p4 PARTITION OF part_hash.t97 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t97_p5 PARTITION OF part_hash.t97 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t97_p6 PARTITION OF part_hash.t97 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t97_p7 PARTITION OF part_hash.t97 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t98 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bigint
    ,c3 varchar(18)
    ,c4 varchar(10)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t98_p0 PARTITION OF part_hash.t98 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE part_hash.t98_p1 PARTITION OF part_hash.t98 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE part_hash.t98_p2 PARTITION OF part_hash.t98 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE part_hash.t98_p3 PARTITION OF part_hash.t98 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE part_hash.t98_p4 PARTITION OF part_hash.t98 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE part_hash.t98_p5 PARTITION OF part_hash.t98 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE part_hash.t98_p6 PARTITION OF part_hash.t98 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE part_hash.t98_p7 PARTITION OF part_hash.t98 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

CREATE TABLE part_hash.t99 (
    id BIGSERIAL
    ,c1 integer
    ,c2 bigint
    ,c3 bytea
    ,c4 jsonb
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t99_p0 PARTITION OF part_hash.t99 FOR VALUES WITH (MODULUS 5, REMAINDER 0);
CREATE TABLE part_hash.t99_p1 PARTITION OF part_hash.t99 FOR VALUES WITH (MODULUS 5, REMAINDER 1);
CREATE TABLE part_hash.t99_p2 PARTITION OF part_hash.t99 FOR VALUES WITH (MODULUS 5, REMAINDER 2);
CREATE TABLE part_hash.t99_p3 PARTITION OF part_hash.t99 FOR VALUES WITH (MODULUS 5, REMAINDER 3);
CREATE TABLE part_hash.t99_p4 PARTITION OF part_hash.t99 FOR VALUES WITH (MODULUS 5, REMAINDER 4);

CREATE TABLE part_hash.t100 (
    id BIGSERIAL
    ,c1 integer
    ,c2 char(5)
    ,c3 varchar(21)
    ,PRIMARY KEY (id, c1)
) PARTITION BY HASH (c1);

CREATE TABLE part_hash.t100_p0 PARTITION OF part_hash.t100 FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE part_hash.t100_p1 PARTITION OF part_hash.t100 FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE part_hash.t100_p2 PARTITION OF part_hash.t100 FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE part_hash.t100_p3 PARTITION OF part_hash.t100 FOR VALUES WITH (MODULUS 4, REMAINDER 3);
