CREATE OR REPLACE FUNCTION part_hash.f_t1()
RETURNS SETOF part_hash.t1
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t1 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t2()
RETURNS SETOF part_hash.t2
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t2 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t3()
RETURNS SETOF part_hash.t3
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t3 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t4()
RETURNS SETOF part_hash.t4
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t4 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t5()
RETURNS SETOF part_hash.t5
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t5 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t6()
RETURNS SETOF part_hash.t6
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t6 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t7()
RETURNS SETOF part_hash.t7
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t7 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t8()
RETURNS SETOF part_hash.t8
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t8 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t9()
RETURNS SETOF part_hash.t9
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t9 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t10()
RETURNS SETOF part_hash.t10
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t10 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t11()
RETURNS SETOF part_hash.t11
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t11 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t12()
RETURNS SETOF part_hash.t12
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t12 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t13()
RETURNS SETOF part_hash.t13
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t13 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t14()
RETURNS SETOF part_hash.t14
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t14 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t15()
RETURNS SETOF part_hash.t15
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t15 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t16()
RETURNS SETOF part_hash.t16
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t16 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t17()
RETURNS SETOF part_hash.t17
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t17 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t18()
RETURNS SETOF part_hash.t18
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t18 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t19()
RETURNS SETOF part_hash.t19
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t19 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t20()
RETURNS SETOF part_hash.t20
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t20 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t21()
RETURNS SETOF part_hash.t21
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t21 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t22()
RETURNS SETOF part_hash.t22
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t22 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t23()
RETURNS SETOF part_hash.t23
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t23 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t24()
RETURNS SETOF part_hash.t24
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t24 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t25()
RETURNS SETOF part_hash.t25
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t25 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t26()
RETURNS SETOF part_hash.t26
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t26 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t27()
RETURNS SETOF part_hash.t27
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t27 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t28()
RETURNS SETOF part_hash.t28
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t28 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t29()
RETURNS SETOF part_hash.t29
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t29 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t30()
RETURNS SETOF part_hash.t30
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t30 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t31()
RETURNS SETOF part_hash.t31
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t31 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t32()
RETURNS SETOF part_hash.t32
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t32 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t33()
RETURNS SETOF part_hash.t33
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t33 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t34()
RETURNS SETOF part_hash.t34
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t34 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t35()
RETURNS SETOF part_hash.t35
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t35 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t36()
RETURNS SETOF part_hash.t36
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t36 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t37()
RETURNS SETOF part_hash.t37
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t37 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t38()
RETURNS SETOF part_hash.t38
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t38 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t39()
RETURNS SETOF part_hash.t39
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t39 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t40()
RETURNS SETOF part_hash.t40
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t40 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t41()
RETURNS SETOF part_hash.t41
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t41 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t42()
RETURNS SETOF part_hash.t42
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t42 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t43()
RETURNS SETOF part_hash.t43
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t43 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t44()
RETURNS SETOF part_hash.t44
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t44 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t45()
RETURNS SETOF part_hash.t45
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t45 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t46()
RETURNS SETOF part_hash.t46
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t46 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t47()
RETURNS SETOF part_hash.t47
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t47 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t48()
RETURNS SETOF part_hash.t48
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t48 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t49()
RETURNS SETOF part_hash.t49
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t49 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t50()
RETURNS SETOF part_hash.t50
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t50 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t51()
RETURNS SETOF part_hash.t51
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t51 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t52()
RETURNS SETOF part_hash.t52
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t52 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t53()
RETURNS SETOF part_hash.t53
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t53 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t54()
RETURNS SETOF part_hash.t54
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t54 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t55()
RETURNS SETOF part_hash.t55
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t55 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t56()
RETURNS SETOF part_hash.t56
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t56 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t57()
RETURNS SETOF part_hash.t57
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t57 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t58()
RETURNS SETOF part_hash.t58
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t58 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t59()
RETURNS SETOF part_hash.t59
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t59 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t60()
RETURNS SETOF part_hash.t60
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t60 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t61()
RETURNS SETOF part_hash.t61
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t61 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t62()
RETURNS SETOF part_hash.t62
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t62 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t63()
RETURNS SETOF part_hash.t63
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t63 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t64()
RETURNS SETOF part_hash.t64
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t64 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t65()
RETURNS SETOF part_hash.t65
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t65 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t66()
RETURNS SETOF part_hash.t66
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t66 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t67()
RETURNS SETOF part_hash.t67
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t67 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t68()
RETURNS SETOF part_hash.t68
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t68 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t69()
RETURNS SETOF part_hash.t69
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t69 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t70()
RETURNS SETOF part_hash.t70
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t70 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t71()
RETURNS SETOF part_hash.t71
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t71 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t72()
RETURNS SETOF part_hash.t72
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t72 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t73()
RETURNS SETOF part_hash.t73
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t73 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t74()
RETURNS SETOF part_hash.t74
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t74 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t75()
RETURNS SETOF part_hash.t75
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t75 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t76()
RETURNS SETOF part_hash.t76
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t76 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t77()
RETURNS SETOF part_hash.t77
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t77 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t78()
RETURNS SETOF part_hash.t78
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t78 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t79()
RETURNS SETOF part_hash.t79
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t79 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t80()
RETURNS SETOF part_hash.t80
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t80 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t81()
RETURNS SETOF part_hash.t81
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t81 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t82()
RETURNS SETOF part_hash.t82
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t82 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t83()
RETURNS SETOF part_hash.t83
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t83 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t84()
RETURNS SETOF part_hash.t84
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t84 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t85()
RETURNS SETOF part_hash.t85
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t85 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t86()
RETURNS SETOF part_hash.t86
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t86 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t87()
RETURNS SETOF part_hash.t87
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t87 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t88()
RETURNS SETOF part_hash.t88
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t88 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t89()
RETURNS SETOF part_hash.t89
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t89 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t90()
RETURNS SETOF part_hash.t90
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t90 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t91()
RETURNS SETOF part_hash.t91
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t91 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t92()
RETURNS SETOF part_hash.t92
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t92 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t93()
RETURNS SETOF part_hash.t93
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t93 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t94()
RETURNS SETOF part_hash.t94
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t94 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t95()
RETURNS SETOF part_hash.t95
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t95 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t96()
RETURNS SETOF part_hash.t96
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t96 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t97()
RETURNS SETOF part_hash.t97
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t97 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t98()
RETURNS SETOF part_hash.t98
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t98 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t99()
RETURNS SETOF part_hash.t99
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t99 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION part_hash.f_t100()
RETURNS SETOF part_hash.t100
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM part_hash.t100 LIMIT 5;
END;
$$;
