FROM busybox:latest

# Create a working directory
WORKDIR /app

# Copy your scripts or files
#COPY run.sh /app/run.sh

# Give execute permission
#RUN chmod +x /app/run.sh

# Default command
CMD ["/bin/sh"]

