CREATE OR REPLACE PROCEDURE job2.p_t1(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t1 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t2(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t2 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t3(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t3 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t4(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t4 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t5(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t5 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t6(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t6 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t7(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t7 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t8(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t8 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t9(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t9 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t10(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t10 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t11(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t11 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t12(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t12 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t13(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t13 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t14(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t14 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t15(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t15 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t16(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t16 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t17(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t17 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t18(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t18 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t19(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t19 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t20(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t20 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t21(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t21 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t22(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t22 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t23(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t23 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t24(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t24 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t25(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t25 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t26(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t26 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t27(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t27 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t28(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t28 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t29(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t29 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t30(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t30 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t31(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t31 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t32(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t32 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t33(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t33 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t34(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t34 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t35(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t35 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t36(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t36 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t37(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t37 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t38(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t38 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t39(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t39 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t40(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t40 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t41(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t41 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t42(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t42 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t43(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t43 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t44(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t44 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t45(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t45 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t46(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t46 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t47(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t47 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t48(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t48 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t49(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t49 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t50(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t50 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t51(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t51 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t52(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t52 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t53(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t53 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t54(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t54 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t55(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t55 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t56(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t56 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t57(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t57 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t58(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t58 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t59(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t59 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t60(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t60 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t61(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t61 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t62(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t62 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t63(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t63 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t64(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t64 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t65(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t65 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t66(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t66 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t67(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t67 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t68(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t68 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t69(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t69 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t70(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t70 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t71(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t71 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t72(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t72 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t73(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t73 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t74(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t74 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t75(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t75 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t76(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t76 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t77(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t77 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t78(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t78 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t79(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t79 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t80(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t80 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t81(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t81 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t82(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t82 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t83(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t83 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t84(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t84 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t85(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t85 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t86(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t86 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t87(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t87 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t88(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t88 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t89(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t89 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t90(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t90 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t91(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t91 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t92(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t92 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t93(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t93 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t94(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t94 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t95(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t95 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t96(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t96 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t97(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t97 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t98(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t98 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t99(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t99 LIMIT 5;
END;
$$; 

CREATE OR REPLACE PROCEDURE job2.p_t100(INOUT p_refcur REFCURSOR)
LANGUAGE plpgsql AS $$
BEGIN
    OPEN p_refcur FOR SELECT * FROM job2.t100 LIMIT 5;
END;
$$; 
