CREATE OR REPLACE FUNCTION job2.f_t1()
RETURNS SETOF job2.t1
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t1 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t2()
RETURNS SETOF job2.t2
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t2 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t3()
RETURNS SETOF job2.t3
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t3 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t4()
RETURNS SETOF job2.t4
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t4 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t5()
RETURNS SETOF job2.t5
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t5 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t6()
RETURNS SETOF job2.t6
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t6 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t7()
RETURNS SETOF job2.t7
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t7 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t8()
RETURNS SETOF job2.t8
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t8 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t9()
RETURNS SETOF job2.t9
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t9 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t10()
RETURNS SETOF job2.t10
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t10 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t11()
RETURNS SETOF job2.t11
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t11 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t12()
RETURNS SETOF job2.t12
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t12 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t13()
RETURNS SETOF job2.t13
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t13 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t14()
RETURNS SETOF job2.t14
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t14 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t15()
RETURNS SETOF job2.t15
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t15 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t16()
RETURNS SETOF job2.t16
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t16 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t17()
RETURNS SETOF job2.t17
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t17 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t18()
RETURNS SETOF job2.t18
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t18 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t19()
RETURNS SETOF job2.t19
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t19 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t20()
RETURNS SETOF job2.t20
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t20 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t21()
RETURNS SETOF job2.t21
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t21 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t22()
RETURNS SETOF job2.t22
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t22 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t23()
RETURNS SETOF job2.t23
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t23 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t24()
RETURNS SETOF job2.t24
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t24 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t25()
RETURNS SETOF job2.t25
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t25 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t26()
RETURNS SETOF job2.t26
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t26 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t27()
RETURNS SETOF job2.t27
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t27 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t28()
RETURNS SETOF job2.t28
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t28 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t29()
RETURNS SETOF job2.t29
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t29 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t30()
RETURNS SETOF job2.t30
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t30 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t31()
RETURNS SETOF job2.t31
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t31 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t32()
RETURNS SETOF job2.t32
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t32 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t33()
RETURNS SETOF job2.t33
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t33 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t34()
RETURNS SETOF job2.t34
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t34 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t35()
RETURNS SETOF job2.t35
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t35 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t36()
RETURNS SETOF job2.t36
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t36 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t37()
RETURNS SETOF job2.t37
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t37 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t38()
RETURNS SETOF job2.t38
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t38 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t39()
RETURNS SETOF job2.t39
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t39 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t40()
RETURNS SETOF job2.t40
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t40 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t41()
RETURNS SETOF job2.t41
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t41 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t42()
RETURNS SETOF job2.t42
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t42 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t43()
RETURNS SETOF job2.t43
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t43 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t44()
RETURNS SETOF job2.t44
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t44 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t45()
RETURNS SETOF job2.t45
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t45 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t46()
RETURNS SETOF job2.t46
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t46 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t47()
RETURNS SETOF job2.t47
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t47 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t48()
RETURNS SETOF job2.t48
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t48 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t49()
RETURNS SETOF job2.t49
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t49 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t50()
RETURNS SETOF job2.t50
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t50 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t51()
RETURNS SETOF job2.t51
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t51 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t52()
RETURNS SETOF job2.t52
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t52 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t53()
RETURNS SETOF job2.t53
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t53 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t54()
RETURNS SETOF job2.t54
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t54 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t55()
RETURNS SETOF job2.t55
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t55 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t56()
RETURNS SETOF job2.t56
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t56 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t57()
RETURNS SETOF job2.t57
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t57 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t58()
RETURNS SETOF job2.t58
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t58 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t59()
RETURNS SETOF job2.t59
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t59 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t60()
RETURNS SETOF job2.t60
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t60 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t61()
RETURNS SETOF job2.t61
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t61 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t62()
RETURNS SETOF job2.t62
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t62 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t63()
RETURNS SETOF job2.t63
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t63 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t64()
RETURNS SETOF job2.t64
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t64 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t65()
RETURNS SETOF job2.t65
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t65 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t66()
RETURNS SETOF job2.t66
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t66 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t67()
RETURNS SETOF job2.t67
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t67 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t68()
RETURNS SETOF job2.t68
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t68 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t69()
RETURNS SETOF job2.t69
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t69 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t70()
RETURNS SETOF job2.t70
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t70 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t71()
RETURNS SETOF job2.t71
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t71 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t72()
RETURNS SETOF job2.t72
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t72 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t73()
RETURNS SETOF job2.t73
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t73 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t74()
RETURNS SETOF job2.t74
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t74 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t75()
RETURNS SETOF job2.t75
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t75 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t76()
RETURNS SETOF job2.t76
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t76 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t77()
RETURNS SETOF job2.t77
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t77 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t78()
RETURNS SETOF job2.t78
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t78 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t79()
RETURNS SETOF job2.t79
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t79 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t80()
RETURNS SETOF job2.t80
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t80 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t81()
RETURNS SETOF job2.t81
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t81 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t82()
RETURNS SETOF job2.t82
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t82 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t83()
RETURNS SETOF job2.t83
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t83 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t84()
RETURNS SETOF job2.t84
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t84 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t85()
RETURNS SETOF job2.t85
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t85 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t86()
RETURNS SETOF job2.t86
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t86 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t87()
RETURNS SETOF job2.t87
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t87 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t88()
RETURNS SETOF job2.t88
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t88 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t89()
RETURNS SETOF job2.t89
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t89 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t90()
RETURNS SETOF job2.t90
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t90 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t91()
RETURNS SETOF job2.t91
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t91 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t92()
RETURNS SETOF job2.t92
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t92 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t93()
RETURNS SETOF job2.t93
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t93 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t94()
RETURNS SETOF job2.t94
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t94 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t95()
RETURNS SETOF job2.t95
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t95 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t96()
RETURNS SETOF job2.t96
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t96 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t97()
RETURNS SETOF job2.t97
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t97 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t98()
RETURNS SETOF job2.t98
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t98 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t99()
RETURNS SETOF job2.t99
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t99 LIMIT 5;
END;
$$;

CREATE OR REPLACE FUNCTION job2.f_t100()
RETURNS SETOF job2.t100
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM job2.t100 LIMIT 5;
END;
$$;
